/**
 * Core data structures for the Market Sentinel application.
 */

/**
 * Represents a single message fetched from a Discord channel.
 */
export interface ChatMessage {
  id: string;
  author: string;
  content: string;
  timestamp: Date;
  isBot?: boolean;
}

/**
 * Diagnostic logs for gateway activity monitoring.
 */
export interface LogEntry {
  id: string;
  timestamp: Date;
  level: 'info' | 'error' | 'success' | 'warn';
  message: string;
}

/**
 * The output generated by the Gemini AI analysis engine.
 */
export interface AnalysisResult {
  id: string;
  timestamp: Date;
  sentimentScore: number; // Quantitative sentiment: -1.0 (Bearish) to 1.0 (Bullish)
  summary: string;        // Markdown-formatted qualitative analysis
  groundingUrls: string[]; // Future-proofing for Google Search grounding citations
  themes: string[];       // Top market trends identified in the text
}

/**
 * Connection credentials and behavior settings for the Discord Gateway.
 */
export interface DiscordConfig {
  botToken: string;
  channelId: string;
  useProxy: boolean;
  proxyUrl?: string;
  cfAccessId?: string;     // Cloudflare Access Client ID
  cfAccessSecret?: string; // Cloudflare Access Client Secret
  autoPost: boolean;
  outputChannelId?: string;
}